"""
app.py
Streamlit front end for the RAG research-paper agent.
Run: streamlit run app.py
"""
import os

from dotenv import load_dotenv
load_dotenv()

import streamlit as st

from src.agent import ResearchAgent
from src.rag_core import RAGPipeline

st.set_page_config(page_title="Research Paper Q&A Agent", page_icon="📄", layout="centered")
st.title("📄 Research Paper Q&A Agent")
st.caption("Agentic RAG over your NLP/ML paper corpus — search, summarize, or compare.")

INDEX_PATH = "data/faiss_index"


@st.cache_resource(show_spinner="Loading index and connecting to local Ollama model...")
def get_agent():
    rag = RAGPipeline(index_path=INDEX_PATH)
    return ResearchAgent(rag)


if not os.path.exists(INDEX_PATH):
    st.warning(
        "No FAISS index found. Run ingestion first:\n\n"
        "`python -m src.ingestion`"
    )
    st.stop()

agent = get_agent()

if "history" not in st.session_state:
    st.session_state.history = []

for turn in st.session_state.history:
    with st.chat_message(turn["role"]):
        st.markdown(turn["content"])

query = st.chat_input("Ask about your papers — e.g. 'Summarize Global PIQA' or 'Compare X and Y'")

if query:
    st.session_state.history.append({"role": "user", "content": query})
    with st.chat_message("user"):
        st.markdown(query)
    with st.expander("🔍 Show retrieved chunks (verify grounding)"):
            for c in agent.rag.retrieve(query):
                st.markdown(f"**[{c.source_paper}]** (distance: {c.score:.3f})")
                st.text(c.text[:500])

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            result = agent.handle(query)
        answer = result["answer"]
        sources_line = f"\n\n**Action:** `{result['action']}` · **Sources:** {', '.join(result['sources'])}"
        st.markdown(answer + sources_line)
        st.session_state.history.append({"role": "assistant", "content": answer + sources_line})

with st.sidebar:
    st.header("About")
    st.write(
        "This agent routes each question to one of three actions:\n"
        "- **search** — factual Q&A over the corpus\n"
        "- **summarize** — summarize one paper\n"
        "- **compare** — compare two or more papers\n\n"
        "Retrieval runs over a FAISS index; answers are generated by "
        "a local Ollama model and grounded only in retrieved excerpts."
    )
    if st.button("Clear chat"):
        st.session_state.history = []
        st.rerun()